sudo: required
language: generic 

services: 
  - docker

before_install: 
  - docker build -t big-ed/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true big-ed/docker-react npm run test
