version: '3'
services:
  web:
    stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  # We can create test container to manipulate the interactions available
  # or keep the first one alone and create another container while overriding the init command 
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ['npm', 'run', 'test']